server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://172.17.0.7:3306/foodie-dev-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: w3i9l6l4i2a3m